# Generated by Django 3.2 on 2021-11-21 14:58

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=500)),
                ('bio', models.TextField(blank=True, null=True)),
                ('dislikes', models.ManyToManyField(blank=True, null=True, related_name='dev_dislikes', to='tindev.Dev')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='dev_likes', to='tindev.Dev')),
            ],
        ),
    ]
